name: "Instant Pull Requests"
description: "Automatically create Pull Requests when a branch is pushed to"
author: "CodeCrafters, Inc."
inputs:
  assignees:
    description: "List of assignee usernames (comma-separated) for the Pull Request"
    required: false
    default: "${{ github.actor }}"
  draft:
    description: Whether to mark the Pull Request as a draft
    required: false
    default: "false"
  base-branch:
    required: true
    description: "The base branch for the pull request"
    default: main
  head-branch:
    required: true
    description: "The base branch for the pull request"
    default: "${{ github.ref_name }}"
  github-token:
    description: "Github API token"
    required: true
    default: ${{ github.token }}
outputs:
  pull-request-url:
    description: "Pull request URL"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  color: green
  icon: git-pull-request
